Remove Keycloak SCIM plugin
We are not using this anywhere in production.
Since the latest update of Keycloak, we receive

    java.lang.NoSuchFieldError: Class com.fasterxml.jackson.core.JsonParser$Feature does not have member field 'com.fasterxml.jackson.core.JsonParser$Feature CLEAR_CURRENT_TOKEN_ON_CLOSE'

Here's me guessing that we have a similar situation as reported in https://github.com/keycloak/keycloak/issues/47749.